site_name: Lapidary
site_description: Build Web API clients with python annotations
copyright: © 2024 Rafał Krupiński
repo_url: https://github.com/python-lapidary/lapidary

nav:
- index.md
- Lapidary runtime: '!include docs/lapidary/config/mkdocs.yml'
- Lapidary render: '!include docs/lapidary-render/config/mkdocs.yml'
plugins:
- monorepo
- mkdocstrings:
    handlers:
      python:
        paths:
        - docs/lapidary/src
        - docs/lapidary-render/src
        options:
          docstring_style: sphinx

theme:
  name: material
  logo: logo.svg
  favicon: logo.svg
  language: en
  features:
  - navigation.instant
  - navigation.sections
  plugins:
  - privacy
  custom_dir: theme
markdown_extensions:
- admonition
- tables
- pymdownx.tasklist

extra:
  analytics:
    provider: goatcounter
    code: lapidary
