site_name: Lapidary
site_description: Build Web API clients with python annotations
copyright: © 2024 Rafał Krupiński
repo_url: https://github.com/python-lapidary/lapidary
repo_name: python-lapidary/lapidary
edit_uri: ''

docs_dir: ../docs
site_dir: ../site
site_url: https://lapidary.dev/

nav:
- Lapidary: index.md
- Usage:
  - usage/client.md
  - usage/operation.md
  - usage/auth.md
- OpenAPI:
  - openapi/index.md
  - openapi/request_body.md

plugins:
- mkdocstrings:
    handlers:
      python:
        paths:
        - ../src
        options:
          docstring_style: sphinx

theme:
  name: material
  logo: logo.svg
  favicon: logo.png
  language: en
  features:
  - navigation.instant
  - navigation.sections
  plugins:
  - privacy
  custom_dir: theme
markdown_extensions:
- admonition
- tables
- pymdownx.tasklist

extra:
  analytics:
    provider: goatcounter
    code: lapidary
